import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { xanhMono, workSans } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${xanhMono.variable} ${workSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
